[data]

[data.eddb]
type = "aixm"
#source = "aixm:dfs:0:EDDB AerodromeMapping"
source = "https://aip.dfs.de/datasets/scripts/getItem.php?amdt=9999&content=aerodrome_mapping/EDDB_AerodromeMapping_2024-05-16_2024-05-16_snapshot.zip"

[data.eddh]
type = "aixm"
#source = "aixm:dfs:0:EDDH AerodromeMapping"
source = "https://aip.dfs.de/datasets/scripts/getItem.php?amdt=9999&content=aerodrome_mapping/EDDH_AerodromeMapping_2024-05-16_2024-05-16_snapshot.zip"

[data.eddv]
type = "aixm"
#source = "aixm:dfs:0:EDDV AerodromeMapping"
source = "https://aip.dfs.de/datasets/scripts/getItem.php?amdt=9999&content=aerodrome_mapping/EDDV_AerodromeMapping_2024-05-16_2024-05-16_snapshot.zip"

[data.edhi]
type = "aixm"
#source = "aixm:dfs:0:EDHI AerodromeMapping"
source = "https://aip.dfs.de/datasets/scripts/getItem.php?amdt=9999&content=aerodrome_mapping/EDHI_AerodromeMapping_2024-05-16_2024-05-16_snapshot.zip"

[data.edhl]
type = "aixm"
#source = "aixm:dfs:0:EDHL AerodromeMapping"
source = "https://aip.dfs.de/datasets/scripts/getItem.php?amdt=9999&content=aerodrome_mapping/EDHL_AerodromeMapping_2024-05-16_2024-05-16_snapshot.zip"

[data.edve]
type = "aixm"
#source = "aixm:dfs:0:EDVE AerodromeMapping"
source = "https://aip.dfs.de/datasets/scripts/getItem.php?amdt=9999&content=aerodrome_mapping/EDVE_AerodromeMapping_2024-05-16_2024-05-16_snapshot.zip"

#[data.rivers]
#type = "kml"
#source = "kml/Rivers.kml"

#[data.eddb_kml]
#type = "kml"
#source = "kml/eddb.kml"


[profiles]

[profiles.TWR_NIGHT]
maps = [
    { map = "grplugin-phoenix", target = "Plugins/EDWW FIR beta/TWR_NIGHT/GRpluginMaps.txt" },
]
dir = "Plugins/EDWW FIR beta/TWR_NIGHT/"
aliases = [ "dark" ]

[profiles.TWR_DAY]
maps = [
    { map = "grplugin-phoenix", target = "Plugins/EDWW FIR beta/TWR_DAY/GRpluginMaps.txt" },
]
dir = "Plugins/EDWW FIR beta/TWR_DAY/"
aliases = [ "bright" ]

[runways]

[runways.EDDB.25R]
thr = [ 52.377431, 13.526097 ]
bearing = 245
fap = [ 52.448706, 13.829058 ] # UBURU
loc = [ 52.365689, 13.476564 ]

[runways.EDDB.25L]
thr = [ 52.358425, 13.523161 ] 
bearing = 245
fap = [ 52.411089, 13.746475 ] # XANIM
loc = [ 52.343619, 13.460783 ]

[runways.EDDB.07L]
thr = [ 52.367689, 13.485025 ]
bearing = 65
fap = [ 52.295367, 13.182458 ] # ODIDO
loc = [ 52.379442, 13.534594 ]

[runways.EDDB.07R]
thr = [ 52.345433, 13.468428 ]
bearing = 65
fap = [ 52.292308, 13.246033 ] # TEBGO
loc = [ 52.360244, 13.530831 ]