[data]

[data.eddb]
type = "aixm"
#source = "aixm:dfs:0:EDDB AerodromeMapping"
source = "https://aip.dfs.de/datasets/scripts/getItem.php?amdt=9999&content=aerodrome_mapping/EDDB_AerodromeMapping_2024-08-08_2024-08-08_snapshot.zip"

[data.eddh]
type = "aixm"
#source = "aixm:dfs:0:EDDH AerodromeMapping"
source = "https://aip.dfs.de/datasets/scripts/getItem.php?amdt=9999&content=aerodrome_mapping/EDDH_AerodromeMapping_2024-08-08_2024-08-08_snapshot.zip"

[data.eddv]
type = "aixm"
#source = "aixm:dfs:0:EDDV AerodromeMapping"
source = "https://aip.dfs.de/datasets/scripts/getItem.php?amdt=9999&content=aerodrome_mapping/EDDV_AerodromeMapping_2024-08-08_2024-08-08_snapshot.zip"

[data.edhi]
type = "aixm"
#source = "aixm:dfs:0:EDHI AerodromeMapping"
source = "https://aip.dfs.de/datasets/scripts/getItem.php?amdt=9999&content=aerodrome_mapping/EDHI_AerodromeMapping_2024-08-08_2024-08-08_snapshot.zip"

[data.edhl]
type = "aixm"
#source = "aixm:dfs:0:EDHL AerodromeMapping"
source = "https://aip.dfs.de/datasets/scripts/getItem.php?amdt=9999&content=aerodrome_mapping/EDHL_AerodromeMapping_2024-08-08_2024-08-08_snapshot.zip"

[data.edve]
type = "aixm"
#source = "aixm:dfs:0:EDVE AerodromeMapping"
source = "https://aip.dfs.de/datasets/scripts/getItem.php?amdt=9999&content=aerodrome_mapping/EDVE_AerodromeMapping_2024-08-08_2024-08-08_snapshot.zip"

[data.etnw_kml]
type = "kml"
source = "kml/ETNW.kml"
root = "ETNW"

#[data.rivers]
#type = "kml"
#source = "kml/Rivers.kml"

#[data.eddb_kml]
#type = "kml"
#source = "kml/eddb.kml"

[data.mva_summer]
type = "raw"
source = "common/mva_summer.txt"

[data.mva_winter]
type = "raw"
source = "common/mva_winter.txt"

[data.topo_highway]
type = "raw"
source = "common/topo_highway.txt"

[data.topo_river]
type = "raw"
source = "common/topo_river.txt"

[data.topo_lake]
type = "raw"
source = "common/topo_lake.txt"

[data.topo_coast]
type = "raw"
source = "common/topo_coast.txt"

[profiles]

[profiles.EDWW]
maps = [
    { map = "topsky-edww", target = "Plugins/EDWW FIR beta/EDWW/TopSkyMaps.txt" },
]
dir = "Plugins/EDWW FIR beta/EDWW/"

[profiles.EDYY]
maps = [
    { map = "topsky-edyy", target = "Plugins/EDWW FIR beta/EDYY/TopSkyMaps.txt" },
]
dir = "Plugins/EDWW FIR beta/EDYY/"

[profiles.EDUU]
maps = [
    { map = "topsky-eduu", target = "Plugins/EDWW FIR beta/EDUU/TopSkyMaps.txt" },
]
dir = "Plugins/EDWW FIR beta/EDUU/"

[profiles.TWR_NIGHT]
maps = [
    { map = "grplugin-phoenix", target = "Plugins/EDWW FIR beta/TWR_NIGHT/GRpluginMaps.txt" },
    { map = "grplugin-stands", target = "Plugins/EDWW FIR beta/TWR_NIGHT/GRpluginStands.txt" },
    { map = "grplugin-settings", target = "Plugins/EDWW FIR beta/TWR_NIGHT/GRpluginSettings.txt" },
    { map = "topsky-phoenix", target = "Plugins/EDWW FIR beta/TWR_NIGHT/TopSkyMaps.txt" },
    { map = "topsky-phoenix-settings", target = "Plugins/EDWW FIR beta/TWR_NIGHT/TopSkySettings.txt" },
]
dir = "Plugins/EDWW FIR beta/TWR_NIGHT/"
aliases = [ "dark" ]

[profiles.TWR_DAY]
maps = [
    { map = "grplugin-phoenix", target = "Plugins/EDWW FIR beta/TWR_DAY/GRpluginMaps.txt" },
    { map = "grplugin-stands", target = "Plugins/EDWW FIR beta/TWR_DAY/GRpluginStands.txt" },
    { map = "grplugin-settings", target = "Plugins/EDWW FIR beta/TWR_DAY/GRpluginSettings.txt" },
    { map = "topsky-phoenix", target = "Plugins/EDWW FIR beta/TWR_DAY/TopSkyMaps.txt" },
    { map = "topsky-phoenix-settings", target = "Plugins/EDWW FIR beta/TWR_DAY/TopSkySettings.txt" },
]
dir = "Plugins/EDWW FIR beta/TWR_DAY/"
aliases = [ "bright" ]

[runways]

[runways.EDDB.25R]
thr = [ 52.377431, 13.526097 ]
bearing = 245
fap = [ 52.448706, 13.829058 ] # UBURU
loc = [ 52.365689, 13.476564 ]

[runways.EDDB.25L]
thr = [ 52.358425, 13.523161 ] 
bearing = 245
fap = [ 52.411089, 13.746475 ] # XANIM
loc = [ 52.343619, 13.460783 ]

[runways.EDDB.07L]
thr = [ 52.367689, 13.485025 ]
bearing = 65
fap = [ 52.295367, 13.182458 ] # ODIDO
loc = [ 52.379442, 13.534594 ]

[runways.EDDB.07R]
thr = [ 52.345433, 13.468428 ]
bearing = 65
fap = [ 52.292308, 13.246033 ] # TEBGO
loc = [ 52.360244, 13.530831 ]